Document: picar
Title: Debian picar Manual
Author: <insert document author here>
Abstract: This manual describes what picar is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/picar/picar.sgml.gz

Format: postscript
Files: /usr/share/doc/picar/picar.ps.gz

Format: text
Files: /usr/share/doc/picar/picar.text.gz

Format: HTML
Index: /usr/share/doc/picar/html/index.html
Files: /usr/share/doc/picar/html/*.html
